# config example

clusters:
  - name: one
    prefix: "/one/"
    upstreams:
      - "host.docker.internal:3000"
      - "host.docker.internal:3001"
  - name: two
    prefix: "/two/"
    upstreams:
      - "host.docker.internal:3002"
      - "host.docker.internal:3003"
