# gateway configuration
#version: 2
#daemon: true
error_log: true
#pid_file: "path to process id file"
#upgrade_sock: "path to upgrade socket"
#user: "user"
#group: "group"
#threads: 10
#work_stealing: true
#ca_file: "path to ca file"
#grace_period_seconds: 10
#graceful_shutdown_timeout: 10
#client_bind_to_ipv4:
#  - "address"
#  - "address"
#client_bind_to_ipv6:
#  - "address"
#  - "address"
#upstream_keepalive_pool_size: 1000
#upstream_connect_offload_threadpools: 100
#upstream_connect_offload_thread_per_pool: 100
#upstream_debug_ssl_keylog: true
clusters:
#  - name: one
#    host: "localhost"
#    tls: false
#    discovery:
#      name: "test-service"
#      passing: true
#    prefix: "/one"
#    rate_limit: 200
#    retry: 3
#    timeout: 2000
#    upstream:
#      - "localhost:3000"
#      - "localhost:3001"
  - name: two
    host: "localhost"
    tls: false
    prefix: "/two"
    rate_limit: 100
    cache:
      memory:
        cache_ttl: 2
        max_size: 5
        max_cache: 10
        lock_timeout: 1000
    retry: 3
    timeout: 2000
    upstream:
      - "localhost:8000"
      - "localhost:8001"
  - name: three
    host: "localhost"
    tls: false
    prefix: "/three"
    rate_limit: 200
    retry: 3
    timeout: 2000
    upstream:
      - "localhost:8000"
      - "localhost:8001"
  - name: four
    host: "localhost"
    tls: false
    prefix: "/four"
    rate_limit: 200
    retry: 3
    timeout: 2000
    upstream:
      - "localhost:8000"
      - "localhost:8001"