# config example

clusters:
  - name: one
    prefix: "/one"
    rate_limit: 5
    upstreams:
      - "localhost:3000"
      - "localhost:3001"
  - name: two
    prefix: "/two"
    rate_limit: 5
    upstreams:
      - "localhost:3002"
      - "localhost:3003"